version: '3.4'
services:
  oef-node:
    image: "fetchai/oef-search:0.7"
    ports:
      - "10000:10000"
      - "20000:20000"
      - "40000:40000"
      - "7500:7500"
    networks:
      main_net:
        ipv4_address: 172.28.1.1
    # logging:
    #   driver: none
    volumes:
      - "../scripts/oef/:/config"
      - "../data/oef-logs:/logs/"
    command:
      - "/config/node_config.json"
    healthcheck:
      interval: 10s
      retries: 5
      test:
      - "CMD-SHELL"
      - "python3"
      - "oef_healthcheck.py"
      - "127.0.0.1"
      - "10000"
      timeout: 5s
    restart: on-failure

  visdom:
    image: "hypnosapos/visdom:latest"
    ports:
      - "8097:8097"
    logging:
      driver: none
    networks:
      main_net:
        ipv4_address: 172.28.1.2


  baseline:
    image: "baseline-image"
    env_file:
      - .env
    depends_on:
      - oef-node
      - visdom
    volumes:
      - ../:/build
    build:
      context: ../
      dockerfile: docker-tac-develop/Dockerfile
    networks:
      main_net:
        ipv4_address: 172.28.1.3
    entrypoint:
      - "pipenv"
      - "run"
      - "sandbox/wait-for-oef.sh"
      - "172.28.1.1"
      - "10000"
      - "python3"
      - "simulation/v1/tac_agent_spawner.py"
      - "--nb-agents"
      - "${NB_AGENTS}"
      - "--nb-goods"
      - "${NB_GOODS}"
      - "--nb-baseline-agents"
      - "${NB_BASELINE_AGENTS}"
      - "--oef-addr"
      - "${OEF_ADDR}"
      - "--oef-port"
      - "${OEF_PORT}"
      - "--data-output-dir"
      - "${DATA_OUTPUT_DIR}"
      - "--version-id"
      - "${VERSION_ID}"
      - "--lower-bound-factor"
      - "${LOWER_BOUND_FACTOR}"
      - "--upper-bound-factor"
      - "${UPPER_BOUND_FACTOR}"
      - "--tx-fee"
      - "${TX_FEE}"
      - "--registration-timeout"
      - "${REGISTRATION_TIMEOUT}"
      - "--inactivity-timeout"
      - "${INACTIVITY_TIMEOUT}"
      - "--competition-timeout"
      - "${COMPETITION_TIMEOUT}"
      - "--services-interval"
      - "${SERVICES_INTERVAL}"
      - "--pending-transaction-timeout"
      - "${PENDING_TRANSACTION_TIMEOUT}"
      - "--register-as"
      - "${REGISTER_AS}"
      - "--search-for"
      - "${SEARCH_FOR}"
      - "--dashboard"
      - "--visdom-addr"
      - "172.28.1.2"
      - "--visdom-port"
      - "8097"
      - "--seed"
      - "${SEED}"
      - "--whitelist-file"
      - "${WHITELIST}"
      - "--version-id"
      - "${VERSION_ID}"
    volumes:
      - type: bind
        source: ${SHARED_DIR}
        target: /build/data/shared
networks:
    main_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16


